# Generated by Django 4.1.4 on 2022-12-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField(default={'en': 'English', 'fr': 'French'}, verbose_name='Article title')),
            ],
        ),
    ]
